#!/bin/bash


cd visualizing/
jamc visualizer.c visualizer.js Box.js car.png access_point.png socket.io.js style.css visualizer.html lots_translated.js fog_locations.js

cd ..

cd allocating/
jamc allocator.c allocator.js

cd ..

cd sensing/
jamc sensor.c sensor.js lots.txt lots_translated.txt

cd ..

cd car/
jamc car.c car.js loading.gif sim.js socket.io.js car.html

cd ..
#taxi_data
