#!/bin/bash


cd ~/JAMSamples/richboy/parking2/visualizing/
jamc visualizer.c visualizer.js Box.js car.png socket.io.js style.css visualizer.html lots_translated.js

cd ~/JAMSamples/richboy/parking2/allocating/
jamc allocator.c allocator.js

cd ~/JAMSamples/richboy/parking2/sensing/
jamc spot.c sensor.js lots.txt lots_translated.txt

cd ~/JAMSamples/richboy/parking2/car/
jamc car.c car.js loading.gif sim.js socket.io.js car.html taxi_data
