#!/bin/bash

#&>/dev/null &
cd ~/JAMSamples/richboy/parking2/
locations=$(cat fog_locations.txt)



cd ~/JAMSamples/richboy/parking2/visualizing/
jam run visualizer.jxe --cloud --app=visualizing --data=127.0.0.1:8379 --bg --log
CNT=0
for location in $locations; do
    let CNT=CNT+1
    longitude=$(cut -f 1 -d ',' <<< "$location")
    latitude=$(cut -f 2 -d ',' <<< "$location")

    jam run visualizer.jxe --fog --app=visualizing --data=127.0.0.1:7379 --loc=$longitude,$latitude --bg --log
    if [ "$CNT = "3" ]; then
        break
    fi
done


cd ~/JAMSamples/richboy/parking2/allocating/
jam run allocator.jxe --cloud --app=allocating --data=127.0.0.1:8379 --bg --log
CNT=0
for location in $locations; do
    let CNT=CNT+1
    longitude=$(cut -f 1 -d ',' <<< "$location")
    latitude=$(cut -f 2 -d ',' <<< "$location")

    jam run allocator.jxe --fog --app=allocating --data=127.0.0.1:7379 --loc=$longitude,$latitude --bg --log
    if [ "$CNT = "3" ]; then
        break
    fi
done


cd ~/JAMSamples/richboy/parking2/sensing/
CNT=0
for location in $locations; do
    let CNT=CNT+1
    longitude=$(cut -f 1 -d ',' <<< "$location")
    latitude=$(cut -f 2 -d ',' <<< "$location")

    jam run sensor.jxe --fog --app=sensing --data=127.0.0.1:7379 --bg --log --loc=$longitude,$latitude
    if [ "$CNT = "3" ]; then
        break
    fi
done

#launch for the parking spots
COUNTER=0
while IFS='' read -r line || [[ -n "$line" ]]; do
	let COUNTER=COUNTER+1
	if [ "$COUNTER" = "1" ]; then
		continue
	fi

	#REMOVE THIS
	if [ "$COUNTER" = "3" ]; then
        break
    fi

	lotID=$(echo $line | cut -f 1 -d '@')
	num=$(echo $line | cut -f 3 -d '@')
	lat=$(echo $line | cut -f 14 -d '@')
	lon=$(echo $line | cut -f 15 -d '@')

	#for i in `seq 1 $num`; do
		jam run sensor.jxe --app=sensing --num=$num --tags=$lotID\_$num --bg --log --loc=$lon,$lat --link=near
	#done
	break
done < "lots_translated.txt"


cd ~/JAMSamples/richboy/parking2/car/

CNT=0
for location in $locations; do
    let CNT=CNT+1
    longitude=$(cut -f 1 -d ',' <<< "$location")
    latitude=$(cut -f 2 -d ',' <<< "$location")

    jam run car.jxe --fog --app=car --data=127.0.0.1:7379 --bg --log --loc=$longitude,$latitude
    if [ "$CNT = "3" ]; then
        break
    fi
done

files=$(ls taxi_data)
COUNT=0
for file in $files; do
    let COUNT=COUNT+1

    loc=$(head -1 taxi_data/$file | cut -f 2.3 -d ',')

	jam run car.jxe --app=car --tags=$file --bg --log --link=near --loc=$loc
	if [ "$COUNT" = "5" ]; then
	    break
	fi
done